### ISSUE TITLE
Review source

### ISSUE THREAD

**Issue by ThrivingKings** [ThrivingKings/animo-vanilla#1]
Yo! I decided it deserves it's own repo rather than overwriting the jQuery version. I was wondering if you'd be interested in glancing over some of the code? No need for a serious review but maybe just point out any issues you might see?

**Comment by devinivy** [comment]
It's on, baaby!  Best way to start is probably just to tag me on some PRs.

**Comment by ThrivingKings** [comment]
Okay, thanks! I goofed by not making the initial commit a PR but would you be up for perusing through it (https://github.com/ThrivingKings/animo-vanilla/commit/5fcafe67da509e03a6f12c8abb7af78cf0cd83a9)? There were 2 main goals to my approach: use promises for animations/transitions, and remove the dependency of the custom stylesheet

**Comment by devinivy** [comment]
Did my pass over https://github.com/ThrivingKings/animo-vanilla/commit/5fcafe67da509e03a6f12c8abb7af78cf0cd83a9 .

**Comment by ThrivingKings** [comment]
Hey man, thank-you so much! Great, great, notes! I really appreciate it

**Comment by devinivy** [comment]
No problem!  It looks solid– I look forward to giving it a whirl.  Just a couple days ago @williamwoodruff and I were talking about the need for a tool similar to this.
